apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask-app
  template:
    metadata:
      labels:
        app: python-flask-app
    spec:
      containers:
      - name: python-flask-container
        image: python-flask-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-flask-service
spec:
  type: NodePort
  selector:
    app: python-flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007  # Puesto que Kubernetes expondrá para acceder desde tu máquina local
